import os
import random
import spotipy
from dotenv import load_dotenv
from faker import Faker
from spotipy.oauth2 import SpotifyClientCredentials

# --- SETUP ENVIRONMENT ---
load_dotenv()
CLIENT_ID = os.getenv("SPOTIFY_CLIENT_ID")
CLIENT_SECRET = os.getenv("SPOTIFY_CLIENT_SECRET")
OUTPUT_FILE = "../database/02_dml_spotify_random.sql"
TOTAL_SONGS_WANTED = 100 

# --- INIT ---
if not CLIENT_ID or not CLIENT_SECRET:
    raise ValueError("⚠️ ERROR: Pastikan .env berisi SPOTIFY_CLIENT_ID dan SPOTIFY_CLIENT_SECRET")

sp = spotipy.Spotify(
    auth_manager=SpotifyClientCredentials(
        client_id=CLIENT_ID, client_secret=CLIENT_SECRET
    )
)
fake = Faker("id_ID")

def escape_sql(text):
    if text is None: return "NULL"
    text_str = str(text).replace("'", "''")
    return "'" + text_str + "'"

def get_safe_date(date_str):
    if not date_str or str(date_str).strip() == "": return "2020-01-01"
    parts = str(date_str).split("-")
    if parts[0] == "0000": return "2020-01-01"
    if len(parts) == 1: return f"{parts[0]}-01-01"
    if len(parts) == 2: return f"{parts[0]}-{parts[1]}-01"
    return date_str

def map_collection_type(spotify_type):
    st = spotify_type.lower()
    if "album" in st: return "Album"
    if "single" in st: return "Single"
    if "compilation" in st: return "Compilation"
    return "EP"

def generate_data_safe():
    sql_statements = []

    # --- HEADER ---
    sql_statements.append("/* Script Generated by Python Faker (Full 27 Tables) */")
    sql_statements.append("BEGIN;")
    sql_statements.append("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    
    # CLEANUP
    sql_statements.append(
        """TRUNCATE TABLE 
        USERS, ARTISTS, GENRES, COLLECTIONS, SONGS, PLAYLISTS, 
        RELEASES, COLLECTIONS_SONGS, CREATE_SONGS, SONGS_GENRES, 
        FOLLOW_ARTISTS, FOLLOW_USERS, LISTENS, LIKE_SONGS, REVIEWS, 
        RATE_SONGS, TOURS, ARTISTS_TOURS, SOCIALS, COLLECTION_LIBRARY, 
        PL_LIBRARY, BLOCK_USERS, BLOCKLIST_ARTISTS, LIKE_REVIEWS, 
        ADD_SONGS_PLAYLISTS, COLLECTION_TOP_3_GENRES, ARTIST_PROMOTION 
        RESTART IDENTITY CASCADE;"""
    )

    # --- FETCH SPOTIFY DATA ---
    print("🔎 Mencari data lagu dari Spotify...")
    collected_tracks = []
    attempts = 0
    while len(collected_tracks) < TOTAL_SONGS_WANTED and attempts < 25:
        search_char = random.choice(["a", "e", "i", "o", "u", "love", "night", "feat"])
        offset_val = random.randint(0, 50)
        try:
            results = sp.search(q=search_char, type="track", limit=50, offset=offset_val)
            items = results["tracks"]["items"]
            if items: collected_tracks.extend(items)
        except Exception as e: print(f"⚠️ API Skip: {e}")
        
        seen = set()
        unique = []
        for t in collected_tracks:
            if t['id'] not in seen:
                unique.append(t)
                seen.add(t['id'])
        collected_tracks = unique
        attempts += 1
    
    collected_tracks = collected_tracks[:TOTAL_SONGS_WANTED]
    print(f"✅ Mendapatkan {len(collected_tracks)} lagu unik.")

    # --- MAPPINGS ---
    artist_map = {}     
    album_map = {}       
    genre_map = {}       
    artist_genres_temp = {} 
    artist_releases_map = {} 

    ids = {"users": 1, "artists": 1, "genres": 1, "collections": 1, "songs": 1}

    # ==========================================
    # PART 1: USERS (Table 1)
    # ==========================================
    print("Generating Users...")
    for _ in range(25): # 25 Users
        u_name = fake.unique.user_name()
        email = f"{u_name}_{ids['users']}@example.com" 
        pfp = f"https://ui-avatars.com/api/?name={u_name}&background=random"
        raw_pw = fake.password(length=12)
        safe_pw = raw_pw.replace("'", "''")
        
        sql = f"INSERT INTO USERS (USER_ID, USERNAME, USER_EMAIL, PW_HASH, USER_PFP, REGION, COUNTRY) VALUES ({ids['users']}, {escape_sql(u_name)}, {escape_sql(email)}, crypt('{safe_pw}', gen_salt('bf')), {escape_sql(pfp)}, {escape_sql(fake.state())}, 'Indonesia');"
        sql_statements.append(sql)
        ids["users"] += 1

    # ==========================================
    # PART 2: METADATA (Tables 2-12 + Trigger Table 25)
    # ==========================================
    print("Processing Metadata...")
    for track in collected_tracks:
        if not track: continue

        # --- ARTIST (Table 2) & GENRES (Table 3) ---
        sp_artist = track["artists"][0]
        sp_artist_id = sp_artist["id"]
        db_artist_id = artist_map.get(sp_artist_id)

        if not db_artist_id:
            try: full_artist = sp.artist(sp_artist_id)
            except: continue 

            db_artist_id = ids["artists"]
            artist_map[sp_artist_id] = db_artist_id
            name = full_artist["name"][:250]
            pfp = full_artist["images"][0]["url"] if full_artist["images"] else ""
            
            sql = f"INSERT INTO ARTISTS (ARTIST_ID, ARTIST_NAME, ARTIST_PFP, MONTHLY_LISTENER_COUNT, ARTIST_EMAIL) VALUES ({db_artist_id}, {escape_sql(name)}, {escape_sql(pfp)}, {full_artist['followers']['total']}, 'contact.{db_artist_id}@label.com') ON CONFLICT DO NOTHING;"
            sql_statements.append(sql)
            ids["artists"] += 1

            temp_genres = []
            for g_name in full_artist["genres"]:
                temp_genres.append(g_name)
                if g_name not in genre_map:
                    g_id = ids["genres"]
                    genre_map[g_name] = g_id
                    sql_g = f"INSERT INTO GENRES (GENRE_ID, GENRE_NAME) VALUES ({g_id}, {escape_sql(g_name)}) ON CONFLICT DO NOTHING;"
                    sql_statements.append(sql_g)
                    ids["genres"] += 1
            artist_genres_temp[sp_artist_id] = temp_genres

        # --- COLLECTION (Table 4) & RELEASES (Table 8) ---
        sp_album = track["album"]
        sp_album_id = sp_album["id"]
        db_album_id = album_map.get(sp_album_id)

        if not db_album_id:
            db_album_id = ids["collections"]
            album_map[sp_album_id] = db_album_id
            title = sp_album["name"][:250]
            date = get_safe_date(sp_album["release_date"])
            cover = sp_album["images"][0]["url"] if sp_album["images"] else ""
            
            sql = f"INSERT INTO COLLECTIONS (COLLECTION_ID, COLLECTION_TITLE, COLLECTION_TYPE, COLLECTION_RELEASE_DATE, COLLECTION_COVER, ISPRERELEASE) VALUES ({db_album_id}, {escape_sql(title)}, {escape_sql(map_collection_type(sp_album['album_type']))}, {escape_sql(date)}, {escape_sql(cover)}, FALSE) ON CONFLICT DO NOTHING;"
            sql_statements.append(sql)
            ids["collections"] += 1

            sql_rel = f"INSERT INTO RELEASES (ARTIST_ID, COLLECTION_ID) VALUES ({db_artist_id}, {db_album_id}) ON CONFLICT DO NOTHING;"
            sql_statements.append(sql_rel)
            
            if db_artist_id not in artist_releases_map: artist_releases_map[db_artist_id] = []
            artist_releases_map[db_artist_id].append(db_album_id)

        # --- SONG (Table 5) ---
        db_song_id = ids["songs"]
        title = track["name"][:250]
        dur = int(track["duration_ms"] / 1000)
        file_path = track["preview_url"] if track["preview_url"] else "/stream/audio_default.mp3"
        
        sql = f"""INSERT INTO SONGS (SONG_ID, SONG_TITLE, SONG_DURATION, SONG_FILE, POPULARITY, VALENCE, ACCOUSTICNESS, DANCEABILITY, ENERGY, SONG_RELEASE_DATE) 
                  VALUES ({db_song_id}, {escape_sql(title)}, {dur}, {escape_sql(file_path)}, {track['popularity']}, {round(random.random(),3)}, {round(random.random(),3)}, {round(random.random(),3)}, {round(random.random(),3)}, {escape_sql(get_safe_date(track['album']['release_date']))}) ON CONFLICT DO NOTHING;"""
        sql_statements.append(sql)

        # --- SONGS_GENRES (Table 11 - FIX ORDER FOR TRIGGER) ---
        assigned_genres = []
        if sp_artist_id in artist_genres_temp and artist_genres_temp[sp_artist_id]:
            assigned_genres = random.sample(artist_genres_temp[sp_artist_id], k=min(2, len(artist_genres_temp[sp_artist_id])))
        if not assigned_genres and genre_map:
            assigned_genres = random.sample(list(genre_map.keys()), k=min(2, len(genre_map)))

        for g_name in assigned_genres:
            if g_name in genre_map:
                sql_sg = f"INSERT INTO SONGS_GENRES (SONG_ID, GENRE_ID) VALUES ({db_song_id}, {genre_map[g_name]}) ON CONFLICT DO NOTHING;"
                sql_statements.append(sql_sg)

        # --- COLLECTIONS_SONGS (Table 10) -> TRIGGERS Table 25 ---
        sql_cs = f"INSERT INTO COLLECTIONS_SONGS (COLLECTION_ID, SONG_ID, NOMOR_DISC, NOMOR_TRACK) VALUES ({db_album_id}, {db_song_id}, {track['disc_number']}, {track['track_number']}) ON CONFLICT DO NOTHING;"
        sql_statements.append(sql_cs)

        # --- CREATE_SONGS (Table 9) ---
        sql_cr = f"INSERT INTO CREATE_SONGS (ARTIST_ID, SONG_ID) VALUES ({db_artist_id}, {db_song_id}) ON CONFLICT DO NOTHING;"
        sql_statements.append(sql_cr)

        ids["songs"] += 1

    # ==========================================
    # PART 3: TRANSACTIONS & INTERACTIONS
    # ==========================================
    print("Generating Transactions...")
    valid_users = list(range(1, ids["users"]))
    valid_songs = list(range(1, ids["songs"]))
    valid_cols = list(range(1, ids["collections"]))
    valid_arts = list(range(1, ids["artists"]))

    # 13. PLAYLISTS & 14. ADD_SONGS_PLAYLISTS
    pl_counter = 1
    if valid_users:
        for u_id in valid_users:
            for _ in range(random.randint(1, 2)):
                pl_title = fake.sentence(nb_words=3).replace(".", "")
                sql = f"INSERT INTO PLAYLISTS (PLAYLIST_ID, USER_ID, PLAYLIST_TITLE, ISPUBLIC, ISCOLLABORATIVE, PLAYLIST_DESC, ISONPROFILE, PLAYLIST_DATE_CREATED) VALUES ({pl_counter}, {u_id}, {escape_sql(pl_title)}, TRUE, FALSE, 'My playlist', TRUE, '{fake.date_this_year()}');"
                sql_statements.append(sql)

                if valid_songs:
                    songs_to_add = random.sample(valid_songs, k=random.randint(3, 8))
                    for idx, s_id in enumerate(songs_to_add, 1):
                        sql_add = f"INSERT INTO ADD_SONGS_PLAYLISTS (PLAYLIST_ID, SONG_ID, NO_URUT, USER_ID) VALUES ({pl_counter}, {s_id}, {idx}, {u_id});"
                        sql_statements.append(sql_add)
                pl_counter += 1

    # 15. LISTENS & 16. LIKE_SONGS
    if valid_users and valid_songs:
        for _ in range(250):
            sql = f"INSERT INTO LISTENS (USER_ID, SONG_ID, DURATION_LISTENED, \"TIMESTAMP\") VALUES ({random.choice(valid_users)}, {random.choice(valid_songs)}, {random.randint(10,300)}, '{fake.date_time_between(start_date='-6m')}');"
            sql_statements.append(sql)
        for u in valid_users:
            for s in random.sample(valid_songs, k=5):
                sql_statements.append(f"INSERT INTO LIKE_SONGS (USER_ID, SONG_ID) VALUES ({u}, {s}) ON CONFLICT DO NOTHING;")

    # 17. RATE_SONGS (YANG TADI HILANG)
    if valid_users and valid_songs:
        for u in valid_users:
            for s in random.sample(valid_songs, k=3):
                sql_statements.append(f"INSERT INTO RATE_SONGS (USER_ID, SONG_ID, SONG_RATING) VALUES ({u}, {s}, {random.randint(1,100)}) ON CONFLICT DO NOTHING;")

    # 18. REVIEWS & 19. LIKE REVIEWS
    total_reviews = 0
    if valid_users and valid_cols:
        for u in valid_users:
            for c in random.sample(valid_cols, k=random.randint(1, 2)):
                sql = f"INSERT INTO REVIEWS (USER_ID, COLLECTION_ID, RATING, REVIEW) VALUES ({u}, {c}, {random.randint(20,100)}, {escape_sql(fake.sentence())});"
                sql_statements.append(sql)
                total_reviews += 1
    if total_reviews > 0:
        for _ in range(30):
            sql_statements.append(f"INSERT INTO LIKE_REVIEWS (REVIEW_ID, USER_ID) VALUES ({random.randint(1, total_reviews)}, {random.choice(valid_users)}) ON CONFLICT DO NOTHING;")

    # 6. TOURS (Table 6), ARTISTS_TOURS (Table 12), SOCIALS (Table 7)
    tour_cnt = 1
    for _ in range(5):
        sql = f"INSERT INTO TOURS (TOUR_ID, TOUR_DATE, TOUR_NAME, VENUE) VALUES ({tour_cnt}, '{fake.date_between(start_date='today', end_date='+1y')}', '{fake.city()} Tour', '{fake.company()} Arena');"
        sql_statements.append(sql)
        if valid_arts:
            for a in random.sample(valid_arts, k=random.randint(1,2)):
                sql_statements.append(f"INSERT INTO ARTISTS_TOURS (TOUR_ID, ARTIST_ID) VALUES ({tour_cnt}, {a}) ON CONFLICT DO NOTHING;")
        tour_cnt += 1
    
    if valid_arts:
        soc_cnt = 1
        for a in valid_arts:
             sql_statements.append(f"INSERT INTO SOCIALS (SOCIAL_ID, ARTIST_ID, SOCIAL_MEDIA_LINK) VALUES ({soc_cnt}, {a}, 'https://instagram.com/artist_{a}') ON CONFLICT DO NOTHING;")
             soc_cnt += 1

    # 20. FOLLOW_ARTISTS & 21. FOLLOW_USERS (YANG TADI HILANG)
    if valid_users and valid_arts:
        for u in valid_users:
            # Follow Artist
            for a in random.sample(valid_arts, k=3):
                sql_statements.append(f"INSERT INTO FOLLOW_ARTISTS (USER_ID, ARTIST_ID) VALUES ({u}, {a}) ON CONFLICT DO NOTHING;")
            # Follow User
            targets = random.sample(valid_users, k=2)
            for t in targets:
                if u != t:
                     sql_statements.append(f"INSERT INTO FOLLOW_USERS (FOLLOWER_ID, FOLLOWED_ID) VALUES ({u}, {t}) ON CONFLICT DO NOTHING;")

    # 22. COLLECTION_LIBRARY & 23. PL_LIBRARY
    if valid_users:
        for u in valid_users:
            if valid_cols:
                sql_statements.append(f"INSERT INTO COLLECTION_LIBRARY (USER_ID, COLLECTION_ID) VALUES ({u}, {random.choice(valid_cols)}) ON CONFLICT DO NOTHING;")
            if pl_counter > 2:
                sql_statements.append(f"INSERT INTO PL_LIBRARY (USER_ID, PLAYLIST_ID) VALUES ({u}, {random.randint(1, pl_counter-1)}) ON CONFLICT DO NOTHING;")

    # 24. ARTIST_PROMOTION
    for a_id, albums in artist_releases_map.items():
        if random.random() > 0.6:
            sql = f"INSERT INTO ARTIST_PROMOTION (ARTIST_ID, COLLECTION_ID, KOMENTAR_PROMOSI) VALUES ({a_id}, {random.choice(albums)}, 'Check my new stuff!') ON CONFLICT DO NOTHING;"
            sql_statements.append(sql)

    # 26. BLOCK_USERS & 27. BLOCKLIST_ARTISTS (YANG TADI HILANG)
    if len(valid_users) > 5:
        for _ in range(5):
             u1, u2 = random.sample(valid_users, 2)
             sql_statements.append(f"INSERT INTO BLOCK_USERS (BLOCKER_ID, BLOCKED_ID) VALUES ({u1}, {u2}) ON CONFLICT DO NOTHING;")
    
    if valid_users and valid_arts:
        for _ in range(5):
             sql_statements.append(f"INSERT INTO BLOCKLIST_ARTISTS (ARTIST_ID, USER_ID) VALUES ({random.choice(valid_arts)}, {random.choice(valid_users)}) ON CONFLICT DO NOTHING;")

    # --- RESET SEQUENCES ---
    print("Resetting Sequences...")
    seq_tables = [
        "USERS", "ARTISTS", "GENRES", "COLLECTIONS", "SONGS", "REVIEWS", "PLAYLISTS", 
        "SOCIALS", "TOURS", "LISTENS", "ADD_SONGS_PLAYLISTS"
    ]
    for t in seq_tables:
        if t == "ADD_SONGS_PLAYLISTS": seq_name, col_id = "seq_add_songs_playlist_id", "ADD_SONG_PL_ID"
        else: seq_name, col_id = f"seq_{t.lower()}_id", f"{t[:-1]}_ID"
        sql = f"SELECT setval('{seq_name}', (SELECT MAX({col_id}) FROM {t}));"
        sql_statements.append(sql)

    sql_statements.append("COMMIT;")

    # --- SAVE ---
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(sql_statements))
    print(f"🎉 Selesai! File '{OUTPUT_FILE}' siap. Total 27/27 Tabel terisi.")

if __name__ == "__main__":
    generate_data_safe()