
DROP VIEW IF EXISTS VIEW_TOP_CHARTS CASCADE;

CREATE OR REPLACE VIEW VIEW_TOP_CHARTS AS
WITH SONG_ARTISTS AS (
    SELECT
        CRS.SONG_ID,
        STRING_AGG(DISTINCT A.ARTIST_NAME, ', ' ORDER BY A.ARTIST_NAME) AS ARTISTS
    FROM CREATE_SONGS CRS
    JOIN ARTISTS A ON A.ARTIST_ID = CRS.ARTIST_ID
    GROUP BY CRS.SONG_ID
),
SONG_ALBUM AS (
    SELECT DISTINCT ON (CS.SONG_ID)
        CS.SONG_ID,
        C.COLLECTION_TITLE AS ALBUM
    FROM COLLECTIONS_SONGS CS
    LEFT JOIN COLLECTIONS C ON C.COLLECTION_ID = CS.COLLECTION_ID
    ORDER BY CS.SONG_ID, C.COLLECTION_TITLE
)
SELECT
    ROW_NUMBER() OVER (ORDER BY S.POPULARITY DESC) AS RANK,
    S.SONG_TITLE,
    SA.ARTISTS,
    AL.ALBUM,
    S.POPULARITY
FROM SONGS S
LEFT JOIN SONG_ARTISTS SA ON SA.SONG_ID = S.SONG_ID
LEFT JOIN SONG_ALBUM AL ON AL.SONG_ID = S.SONG_ID
WHERE S.POPULARITY IS NOT NULL
ORDER BY S.POPULARITY DESC;
