DROP VIEW IF EXISTS VIEW_FULL_SONG_DETAILS CASCADE;

CREATE OR REPLACE VIEW VIEW_FULL_SONG_DETAILS AS
SELECT
    S.SONG_ID,
    S.SONG_TITLE,
    STRING_AGG(DISTINCT A.ARTIST_NAME, ', ') AS ARTIST_NAME,
    C.COLLECTION_TITLE AS ALBUM_NAME,
    S.SONG_DURATION,
    S.POPULARITY,
    S.SONG_FILE
FROM SONGS S
-- join ke artis
JOIN CREATE_SONGS CS ON S.SONG_ID = CS.SONG_ID
JOIN ARTISTS A ON CS.ARTIST_ID = A.ARTIST_ID
-- join ke album
LEFT JOIN COLLECTIONS_SONGS C_S ON S.SONG_ID = C_S.SONG_ID
LEFT JOIN COLLECTIONS C ON C_S.COLLECTION_ID = C.COLLECTION_ID
GROUP BY
    -- sisa kolom lain wajib di group-by
    S.SONG_ID,
    S.SONG_TITLE,
    C.COLLECTION_TITLE,
    S.SONG_DURATION,
    S.POPULARITY,
    S.SONG_FILE;
