
DROP VIEW IF EXISTS VIEW_USER_LIBRARY_STATS CASCADE;

CREATE OR REPLACE VIEW VIEW_USER_LIBRARY_STATS AS
WITH PUB_PLAYLISTS AS (
    SELECT USER_ID, COUNT(*) AS PUBLIC_PLAYLISTS
    FROM PLAYLISTS
    WHERE ISPUBLIC = TRUE
    GROUP BY USER_ID
),
FOLLOWING_USERS AS (
    SELECT FOLLOWER_ID AS USER_ID, COUNT(*) AS FOLLOW_USERS_COUNT
    FROM FOLLOW_USERS
    GROUP BY FOLLOWER_ID
),
FOLLOWING_ARTISTS AS (
    SELECT USER_ID, COUNT(*) AS FOLLOW_ARTISTS_COUNT
    FROM FOLLOW_ARTISTS
    GROUP BY USER_ID
),
FOLLOWERS AS (
    SELECT FOLLOWED_ID AS USER_ID, COUNT(*) AS FOLLOWERS_COUNT
    FROM FOLLOW_USERS
    GROUP BY FOLLOWED_ID
)
SELECT
    U.USER_ID,
    U.USERNAME,
    U.USER_PFP,

    COALESCE(PP.PUBLIC_PLAYLISTS, 0) AS PUBLIC_PLAYLISTS,

    COALESCE(FU.FOLLOW_USERS_COUNT, 0) +
    COALESCE(FA.FOLLOW_ARTISTS_COUNT, 0) AS FOLLOWING_COUNT,

    COALESCE(FR.FOLLOWERS_COUNT, 0) AS FOLLOWERS_COUNT

FROM USERS U
LEFT JOIN PUB_PLAYLISTS PP ON PP.USER_ID = U.USER_ID
LEFT JOIN FOLLOWING_USERS FU ON FU.USER_ID = U.USER_ID
LEFT JOIN FOLLOWING_ARTISTS FA ON FA.USER_ID = U.USER_ID
LEFT JOIN FOLLOWERS FR ON FR.USER_ID = U.USER_ID;
