
DROP VIEW IF EXISTS VIEW_ARTIST_PROFILE_HEADER CASCADE;

CREATE OR REPLACE VIEW VIEW_ARTIST_PROFILE_HEADER AS
WITH TOTAL_ALBUMS AS (
    SELECT ARTIST_ID, COUNT(*) AS TOTAL_ALBUMS
    FROM RELEASES
    GROUP BY ARTIST_ID
),
TOTAL_TRACKS AS (
    SELECT ARTIST_ID, COUNT(*) AS TOTAL_TRACKS
    FROM CREATE_SONGS
    GROUP BY ARTIST_ID
)
SELECT
    A.ARTIST_ID,
    A.ARTIST_NAME,
    A.BIO,
    A.ARTIST_PFP,
    A.BANNER,
    A.ARTIST_EMAIL,

    A.MONTHLY_LISTENER_COUNT,
    A.FOLLOWER_COUNT,

    COALESCE(ALB.TOTAL_ALBUMS, 0) AS TOTAL_ALBUMS,
    COALESCE(TRK.TOTAL_TRACKS, 0) AS TOTAL_TRACKS

FROM ARTISTS A
LEFT JOIN TOTAL_ALBUMS ALB ON A.ARTIST_ID = ALB.ARTIST_ID
LEFT JOIN TOTAL_TRACKS TRK ON A.ARTIST_ID = TRK.ARTIST_ID;
