DROP VIEW IF EXISTS VIEW_ALBUM_TRACKLIST CASCADE;

CREATE OR REPLACE VIEW VIEW_ALBUM_TRACKLIST AS
WITH
-- 1) Aggregate Album Artists (because some albums have multiple artists)
ALBUM_ARTISTS AS (
    SELECT
        R.COLLECTION_ID,
        STRING_AGG(DISTINCT A.ARTIST_NAME, ', ' ORDER BY A.ARTIST_NAME) AS ALBUM_ARTISTS
    FROM RELEASES R
    JOIN ARTISTS A ON R.ARTIST_ID = A.ARTIST_ID
    GROUP BY R.COLLECTION_ID
),

-- 2) Aggregate Song Artists
SONG_ARTISTS AS (
    SELECT
        CRS.SONG_ID,
        STRING_AGG(DISTINCT A.ARTIST_NAME, ', ' ORDER BY A.ARTIST_NAME) AS SONG_ARTISTS
    FROM CREATE_SONGS CRS
    JOIN ARTISTS A ON CRS.ARTIST_ID = A.ARTIST_ID
    GROUP BY CRS.SONG_ID
)

SELECT
    C.COLLECTION_ID,
    C.COLLECTION_TITLE,
    AA.ALBUM_ARTISTS,

    CS.NOMOR_DISC,
    CS.NOMOR_TRACK,
    S.SONG_TITLE,

    SA.SONG_ARTISTS,

    TO_CHAR((S.SONG_DURATION || ' second')::interval, 'MI:SS') AS DURATION

FROM COLLECTIONS C
JOIN ALBUM_ARTISTS AA ON C.COLLECTION_ID = AA.COLLECTION_ID

JOIN COLLECTIONS_SONGS CS ON C.COLLECTION_ID = CS.COLLECTION_ID
JOIN SONGS S ON CS.SONG_ID = S.SONG_ID
LEFT JOIN SONG_ARTISTS SA ON SA.SONG_ID = S.SONG_ID

ORDER BY
    C.COLLECTION_ID,
    CS.NOMOR_DISC,
    CS.NOMOR_TRACK;
